<?php
        return [
                                                                                ['question' => 'Q. What is your refund policy?', 'answer' => '<p>Summer Dreams Ltd are a UK company operating successfully since 2013 and we were the ONLY event company in Zante who refunded deposits in 2020 and 2021 when flights were cancelled due to Covid. Your deposits are held in a trust account and if your holiday or flight is cancelled we will of course refund you. Please note, no other boat party in Zante will even consider refunding you, even if they cancel due to bad weather or ‘engine problems’.</p>'],
                                                                                        ['question' => 'Q. Is this like a booze cruise?', 'answer' => '<p>No it’s not a booze cruise! We don’t play games with whipped cream and strawberry jam. No sucking on chocolate bars. No condoms on head. We also sail at Sunset – the booze cruises sail in the daytime when everyone is hungover and it’s far too hot. They are also frequently cancelled due to lack of people and always rammed with lads, which doesn’t make for a great boat party.</p>
<p>Booze cruises in Zante also have a ‘no refund’ policy buried in their T’s and C’s which they used to great effect in 2021 when the whole Summer was cancelled.</p>'],
                                                                                        ['question' => 'Q. Are drinking and sex games played onboard?', 'answer' => '<p>No. There are 100% no games played. Fantasy Boat Party is a music event, think of it as a floating night-club. We’ve had top DJ’s and artists like Nathan Dawe, Jamie Duggan, Ramz, Not3s and many more onboard. None of whom would be seen dead on a booze cruise. We have a massive sound system, two dance floors and in the VIP area people are drinking Ciroc and Belvedere and enjoying the scenery and the music. We appreciate there is a market for games, however we don’t cater to it. Please check out our videos and Hall of Fame gallery to get a taste of what to expect.</p>'],
                                                                                        ['question' => 'Q. Why do we need to reserve?', 'answer' => '<p>Our venue is the best available for a boat party in Zante. You can go out to sea on a triple deck Super Yacht with 300 people and enjoy a boat party with a great reputation run by professionals who’ve been doing this for 10 years. Or you can go on a daytime booze cruise, crammed on a boat totally unfit for purpose with one shared toilet.</p>
<p>With up to 10,000 people in resort peak season, we simply don’t have enough spaces to cope with demand which is why you need to reserve. It also means we don’t need to pay commission so we are £10 cheaper than the local booze cruises.</p>'],
                                                                                        ['question' => 'Q. After we pay the deposit when do we pay the balance?', 'answer' => '<p>You pay the balance in resort when you arrive and pick up your tickets and merchandise. You can pay in either sterling or euros, whatever is easiest for you. We can also deliver if you are at the top of the Strip or at a villa somewhere. If you arrive on the day of the event we can organise everything at the pre-party.</p>'],
                                                                                        ['question' => 'Q. Where do we pick up our tickets?', 'answer' => '<p>You pick up your tickets in resort from our office on the main strip at IKON Club. You can either head to our office which most people do when they arrive and have a stroll around, we are slap bang in the middle of the strip and open every day from 10am til late. Or for those of you who are a bit of a hike away, simply call/text and your tickets will be despatched to you via moped courier. 2023 will be our 10th year of handling tens of thousands of reservations so be assured we are very organised.</p>'],
                                                                                        ['question' => 'Q. Is my deposit secure?', 'answer' => '<p>We transact using Paypal so your deposits are fully secured. Unlike EVERY other boat party in Zante, Summer Dreams has NEVER cancelled due to lack of numbers. Last year in August two of the other boat party’s in Zante cancelled the whole month as only 20 odd people had been foolish enough to book. The organisers weren’t even on the island.</p>
<p>In 2020 &amp; 2021 every other event promotor in Zante offered vouchers only when the summer was cancelled. Summer Dreams Zante refunded over 4,000 people – that tells you everything you need to know about who can be trusted to book with in Zante.</p>
<p>Summer Dreams is a UK Ltd company established in 2013 and our reputation is of paramount importance to us. You could dispute your payment on Paypal if you felt we ripped you off so our interest is to deliver a great boat party and we do.</p>'],
                                                                                        ['question' => 'Q. My mates 17 do we need ID?', 'answer' => '<p>A. Good question! 90% of guests are aged 17 – 25 and you can come on if you are 17 no problem. Nowhere in Zante asks for ID and there will be no issue being served or drinking alcohol anywhere in Zante.</p>'],
                                                                                        ['question' => 'Q. How long does the party go on for?', 'answer' => '<p>A. The pre-party starts at 3.30pm at Karma Day Club. Air conditioned coaches begin to arrive 4.15pm and we have everyone onboard by 4.45 pm when we set off. We cruise the coastline, visiting our private beach for a swim stop and beach party, then sail off into the Sunset around 7.45 pm. We get back to Zante around 8.50 pm for the transfer back to Laganas.</p>'],
                                                                                        ['question' => 'Q. Is alcohol included?', 'answer' => '<p>Yes, our crew will get you half way there with our champagne guns and premium vodka shots. For those who wish to get smashed, we offer a subsidised bar which serves QUALITY alcohol only, no Rushkinoff!</p>
<p>You can buy a pint of vodka &amp; mixer or cocktail, a quadruple measure of alcohol for 5 euro or a smaller one for 2.50 euro so about £2. You can also pre order Goose, Belvedere, Moet, Dom P, Absolut or Smirnoff by the bottle at very low prices. We don’t offer a free bar because firstly, there is no such thing – it’s a sales gimmick. A free bar is also not fair! A 16 stone Rugby player can put away 4 times as much alcohol than most people. And also it’s not actually much fun to be on a boat with loads of people smashed out of their faces. Finally, to give everyone onboard unlimited drinks at a decent price we would have to use low quality alcohol and that’s something we’re not prepared to do.</p>'],
                                                                                        ['question' => 'Q. Will I get sea sick?', 'answer' => '<p>No, we are on the leeward side of Zante, the sea is like a lake and the yacht is huge. Nobody has ever been sea sick.</p>'],
                                                                                        ['question' => 'Q. Is food included?', 'answer' => '<p>No we serve no food although we may introduce Pringles this Summer.</p>
<p>We definitely prescribe a light lunch to line the stomach before the pre party.</p>'],
                                                                                        ['question' => 'Q. Where does the yacht leave from?', 'answer' => '<p>The yacht leaves from the Port of Zakynthos – the pick up is from Karma Day Club which is in the middle of the main strip in Laganas where 99.9% of you will be staying. If you are not staying in Laganas we can meet you at the port.</p>'],
                                                                                        ['question' => 'Q. Can i use the Summer Dreams Summer 2022 discount wristband my whole holiday?', 'answer' => '<p>Yes, all our partners will have a poster or banner detailing the Summer Dreams offer, we recommend you pick it up when you arrive so you can start using it straight away. You can save at least €50 over over your weeks holiday which makes buying a Fantasy Boat Party ticket a massive no-brainer.</p>'],
                                                                                        ['question' => 'Q. What does the Summer Dreams newsletter entail?', 'answer' => '<p>Our crew have been in Zante for over 20 years between them and would like to share their top tips and knowledge of the resort with you including very useful information on how to stay safe, not get conned, the best bars, the best beaches, currency exchange etc it’s definitely worth a read.</p>'],
                                                                                        ['question' => 'Q. How do we get the photos?', 'answer' => '<p>HD and watermarked photos will usually go up on Facebook a few days after.</p>'],
];