<?php 

return [
   'header' => [
      [
         "id" => 1, 
         "menu_id" => 1, 
         "name" => "Event Details", 
         "locale" => "en_US", 
         "class" => "Outl1ne\MenuBuilder\MenuItemTypes\MenuItemStaticURLType", 
         "value" => "/event-details", 
         "target" => "_self", 
         "data" => null, 
         "parent_id" => null, 
         "order" => 1, 
         "enabled" => 1, 
         "created_at" => "2023-09-22 13:43:16", 
         "updated_at" => "2023-09-22 13:43:16", 
         "nestable" => 1 
      ], 
   [
            "id" => 2, 
            "menu_id" => 1, 
            "name" => "What to expect", 
            "locale" => "en_US", 
            "class" => "Outl1ne\MenuBuilder\MenuItemTypes\MenuItemStaticURLType", 
            "value" => "/event-details", 
            "target" => "_self", 
            "data" => null, 
            "parent_id" => 1, 
            "order" => 1, 
            "enabled" => 1, 
            "created_at" => "2023-09-22 13:43:41", 
            "updated_at" => "2023-09-22 13:43:43", 
            "nestable" => 1 
         ], 
   [
               "id" => 3, 
               "menu_id" => 1, 
               "name" => "A-List Packages", 
               "locale" => "en_US", 
               "class" => "Outl1ne\MenuBuilder\MenuItemTypes\MenuItemStaticURLType", 
               "value" => "/zante-event-packages", 
               "target" => "_self", 
               "data" => null, 
               "parent_id" => null, 
               "order" => 2, 
               "enabled" => 1, 
               "created_at" => "2023-09-22 13:47:17", 
               "updated_at" => "2023-09-22 13:55:48", 
               "nestable" => 1 
            ], 
   [
                  "id" => 4, 
                  "menu_id" => 1, 
                  "name" => "Zante Guides", 
                  "locale" => "en_US", 
                  "class" => "Outl1ne\MenuBuilder\MenuItemTypes\MenuItemStaticURLType", 
                  "value" => "/blog", 
                  "target" => "_self", 
                  "data" => null, 
                  "parent_id" => null, 
                  "order" => 3, 
                  "enabled" => 1, 
                  "created_at" => "2023-09-22 13:47:17", 
                  "updated_at" => "2023-09-22 13:55:48", 
                  "nestable" => 1 
               ], 
   [
                     "id" => 5, 
                     "menu_id" => 1, 
                     "name" => "Reviews", 
                     "locale" => "en_US", 
                     "class" => "Outl1ne\MenuBuilder\MenuItemTypes\MenuItemStaticURLType", 
                     "value" => "/reviews", 
                     "target" => "_self", 
                     "data" => null, 
                     "parent_id" => 1, 
                     "order" => 2, 
                     "enabled" => 1, 
                     "created_at" => "2023-09-22 13:55:45", 
                     "updated_at" => "2023-09-22 13:55:48", 
                     "nestable" => 1 
                  ], 
   [
                        "id" => 6, 
                        "menu_id" => 1, 
                        "name" => "Gallery", 
                        "locale" => "en_US", 
                        "class" => "Outl1ne\MenuBuilder\MenuItemTypes\MenuItemStaticURLType", 
                        "value" => "/galleries", 
                        "target" => "_self", 
                        "data" => null, 
                        "parent_id" => 1, 
                        "order" => 3, 
                        "enabled" => 1, 
                        "created_at" => "2023-09-22 13:56:03", 
                        "updated_at" => "2023-09-22 13:56:06", 
                        "nestable" => 1 
                     ], 
   [
                           "id" => 7, 
                           "menu_id" => 1, 
                           "name" => "Video", 
                           "locale" => "en_US", 
                           "class" => "Outl1ne\MenuBuilder\MenuItemTypes\MenuItemStaticURLType", 
                           "value" => "/video", 
                           "target" => "_self", 
                           "data" => null, 
                           "parent_id" => 1, 
                           "order" => 4, 
                           "enabled" => 1, 
                           "created_at" => "2023-09-22 13:56:29", 
                           "updated_at" => "2023-09-22 13:56:31", 
                           "nestable" => 1 
                        ], 
   [
                              "id" => 8, 
                              "menu_id" => 1, 
                              "name" => "Discounts", 
                              "locale" => "en_US", 
                              "class" => "Outl1ne\MenuBuilder\MenuItemTypes\MenuItemStaticURLType", 
                              "value" => "/privilege-card", 
                              "target" => "_self", 
                              "data" => null, 
                              "parent_id" => 1, 
                              "order" => 5, 
                              "enabled" => 1, 
                              "created_at" => "2023-09-22 13:56:49", 
                              "updated_at" => "2023-09-22 13:56:51", 
                              "nestable" => 1 
                           ], 
   [
                                 "id" => 9, 
                                 "menu_id" => 1, 
                                 "name" => "FAQS", 
                                 "locale" => "en_US", 
                                 "class" => "Outl1ne\MenuBuilder\MenuItemTypes\MenuItemStaticURLType", 
                                 "value" => "/faqs", 
                                 "target" => "_self", 
                                 "data" => null, 
                                 "parent_id" => 1, 
                                 "order" => 6, 
                                 "enabled" => 1, 
                                 "created_at" => "2023-09-22 13:57:13", 
                                 "updated_at" => "2023-09-22 13:57:16", 
                                 "nestable" => 1 
                              ] 
   ],
   'footer_one' => [
      [
         "menu_id" => 2, 
         "name" => "For Guests", 
         "locale" => "en_US", 
         "class" => "Outl1ne\MenuBuilder\MenuItemTypes\MenuItemTextType", 
         "value" => null, 
         "target" => "_self", 
         "data" => null, 
         "parent_id" => null, 
         "order" => 1, 
         "enabled" => 1, 
         "created_at" => "2023-09-22 13:43:16", 
         "updated_at" => "2023-09-22 13:43:16", 
         "nestable" => 1 
      ], 
      [
         "menu_id" => 2, 
         "name" => "FAQs", 
         "locale" => "en_US", 
         "class" => "Outl1ne\MenuBuilder\MenuItemTypes\MenuItemStaticURLType", 
         "value" => "/faqs", 
         "target" => "_self", 
         "data" => null, 
         "parent_id" => null, 
         "order" => 2, 
         "enabled" => 1, 
         "created_at" => "2023-09-22 13:43:16", 
         "updated_at" => "2023-09-22 13:43:16", 
         "nestable" => 1 
      ], 
   ],
   'footer_two' => [
      [
         "menu_id" => 3, 
         "name" => "Event Details", 
         "locale" => "en_US", 
         "class" => "Outl1ne\MenuBuilder\MenuItemTypes\MenuItemTextType", 
         "value" => null, 
         "target" => "_self", 
         "data" => null, 
         "parent_id" => null, 
         "order" => 1, 
         "enabled" => 1, 
         "created_at" => "2023-09-22 13:43:16", 
         "updated_at" => "2023-09-22 13:43:16", 
         "nestable" => 1 
      ], 
      [
         "menu_id" => 3, 
         "name" => "About Event", 
         "locale" => "en_US", 
         "class" => "Outl1ne\MenuBuilder\MenuItemTypes\MenuItemStaticURLType", 
         "value" => "/event-details", 
         "target" => "_self", 
         "data" => null, 
         "parent_id" => null, 
         "order" => 2, 
         "enabled" => 1, 
         "created_at" => "2023-09-22 13:43:16", 
         "updated_at" => "2023-09-22 13:43:16", 
         "nestable" => 1 
      ], 
      [
         "menu_id" => 3, 
         "name" => "Reviews", 
         "locale" => "en_US", 
         "class" => "Outl1ne\MenuBuilder\MenuItemTypes\MenuItemStaticURLType", 
         "value" => "/reviews", 
         "target" => "_self", 
         "data" => null, 
         "parent_id" => null, 
         "order" => 2, 
         "enabled" => 1, 
         "created_at" => "2023-09-22 13:43:16", 
         "updated_at" => "2023-09-22 13:43:16", 
         "nestable" => 1 
      ], 
      [
         "menu_id" => 3, 
         "name" => "Gallery", 
         "locale" => "en_US", 
         "class" => "Outl1ne\MenuBuilder\MenuItemTypes\MenuItemStaticURLType", 
         "value" => "/galleries", 
         "target" => "_self", 
         "data" => null, 
         "parent_id" => null, 
         "order" => 2, 
         "enabled" => 1, 
         "created_at" => "2023-09-22 13:43:16", 
         "updated_at" => "2023-09-22 13:43:16", 
         "nestable" => 1 
      ], 
      [
         "menu_id" => 3, 
         "name" => "Book Tikets", 
         "locale" => "en_US", 
         "class" => "Outl1ne\MenuBuilder\MenuItemTypes\MenuItemStaticURLType", 
         "value" => "/make-reservation", 
         "target" => "_self", 
         "data" => null, 
         "parent_id" => null, 
         "order" => 2, 
         "enabled" => 1, 
         "created_at" => "2023-09-22 13:43:16", 
         "updated_at" => "2023-09-22 13:43:16", 
         "nestable" => 1 
      ], 
   ],
   'footer_three' => [
      [
         "menu_id" => 4, 
         "name" => "Find out more", 
         "locale" => "en_US", 
         "class" => "Outl1ne\MenuBuilder\MenuItemTypes\MenuItemTextType", 
         "value" => null, 
         "target" => "_self", 
         "data" => null, 
         "parent_id" => null, 
         "order" => 1, 
         "enabled" => 1, 
         "created_at" => "2023-09-22 13:43:16", 
         "updated_at" => "2023-09-22 13:43:16", 
         "nestable" => 1 
      ], 
      [
         "menu_id" => 4, 
         "name" => "Contact", 
         "locale" => "en_US", 
         "class" => "Outl1ne\MenuBuilder\MenuItemTypes\MenuItemStaticURLType", 
         "value" => "/contact", 
         "target" => "_self", 
         "data" => null, 
         "parent_id" => null, 
         "order" => 2, 
         "enabled" => 1, 
         "created_at" => "2023-09-22 13:43:16", 
         "updated_at" => "2023-09-22 13:43:16", 
         "nestable" => 1 
      ], 
   ],
]; 
 
